name: 'github-action-clean-docker-packages'
description: 'Cleans Docker packages store in GitHub'
inputs:
  gh-token:
    description: 'a token that has permissions to read and delete packages'
    required: true
  num-keep:  # id of input
    description: 'the number of Docker packages to keep'
    required: true
    default: 100
  package-name:  # id of input
    description: 'the package to clean in the GitHub repo'
    required: true
  package-type: # id of input
    description: 'the type of package to clean[container/docker]'
    required: true
    default: container
  dry-run: # id of input
    description: 'bool, only print out what would be removed'
    required: true
    default: false
outputs:
  packages-cleaned: # id of output
    description: 'The packages that were cleaned/removed'
runs:
  using: 'node12'
  main: 'src/index.js'
